MvcOnlineCommercialAutomation/Models/Classes/CargoTracking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineCommercialAutomation.Models.Classes
{
    public class CargoTracking
    {
        [Key]
        public int CargoTrackingID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TrackingCode { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Description { get; set; }
        public DateTime CargoTrackingDateTime { get; set; }
    }
}

MvcOnlineCommercialAutomation/Controllers/CargoController.cs
using MvcOnlineCommercialAutomation.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineCommercialAutomation.Controllers
{
    public class CargoController : Controller
    {
        // GET: Cargo
        Context c = new Context();
        public ActionResult Index(string p)
        {
            //var cargos = c.CargoDetails.ToList();
            //return View(cargos);

            var cargos = from x in c.CargoDetails select x;
            if (!string.IsNullOrEmpty(p))
            {
                cargos = cargos.Where(y => y.TrackingCode.Contains(p));
            }
            return View(cargos.ToList());
        }
        [HttpGet]
        public ActionResult NewCargo()
        {
            Random rnd = new Random();
            string[] characters = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" };

            int c1, c2, c3;
            c1 = rnd.Next(0, characters.Length);
            c2 = rnd.Next(0, characters.Length);
            c3 = rnd.Next(0, characters.Length);

            int n1, n2, n3;
            n1 = rnd.Next(100, 1000);
            n2 = rnd.Next(10, 99);
            n3 = rnd.Next(10, 99);

            string code = n1.ToString() + characters[c1] + n2 + characters[c2] + n3 + characters[c3];
            ViewBag.trackingCode = code;
            return View();
        }
        [HttpPost]
        public ActionResult NewCargo(CargoDetail cargo)
        {
            c.CargoDetails.Add(cargo);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CargoTracking(string id)
        {
            var values = c.CargoTrackings.Where(x => x.TrackingCode == id).ToList();
            return View(values);
        }
    }
}

MvcOnlineCommercialAutomation/Views/Cargo/CargoTracking.cshtml
@using MvcOnlineCommercialAutomation.Models.Classes
@model List<CargoTracking>
@{
    ViewBag.Title = "CargoTracking";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Description</td>
            <td>@item.CargoTrackingDateTime</td>
        </tr>
    }
</table>

MvcOnlineCommercialAutomation/Views/Cargo/Index.cshtml
@using MvcOnlineCommercialAutomation.Models.Classes
@model List<CargoDetail>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
@using (Html.BeginForm("Index", "Cargo", FormMethod.Get))
{
    <p>
        Kargo Takip Numarası: @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Takip Kodu</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Employee</td>
            <td>@item.Receiver</td>
            <td>@item.CargoDate</td>
            <td>@item.TrackingCode</td>
            <td><a href="/Cargo/CargoTracking/@item.TrackingCode" class="btn btn-default" style="background-color:lightcoral; color:white">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Cargo/NewCargo/" class="btn btn-info">Yeni Kargo Girişi</a>

MvcOnlineCommercialAutomation/Views/Cargo/NewCargo.cshtml
@model MvcOnlineCommercialAutomation.Models.Classes.CargoDetail
@{
    ViewBag.Title = "NewCargo";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Kargo Bilgisi Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Takip Kodu")
    <input type="text" value="@ViewBag.trackingCode" class="form-control" readonly name="TrackingCode"/>
    <br />
    @Html.Label("Personel")
    @Html.TextBoxFor(x => x.Employee, new { @class = "form-control" })
    <br />
    @Html.Label("Alıcı")
    @Html.TextBoxFor(x => x.Receiver, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    <input type="date" class="form-control" name="CargoDate" />
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>