MvcOnlineCommercialAutomation/Controllers/QRController.cs
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineCommercialAutomation.Controllers
{
    public class QRController : Controller
    {
        // GET: QR
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string code)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator createCode = new QRCodeGenerator();
                QRCodeGenerator.QRCode qrCode = createCode.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);
                using (Bitmap picture = qrCode.GetGraphic(10))
                {
                    picture.Save(ms,ImageFormat.Png);
                    ViewBag.qrCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
        }

    }
}

MvcOnlineCommercialAutomation/Views/QR/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<div>
    @using (Html.BeginForm("Index", "QR", FormMethod.Post))
    {
        <input type="text" name="code"/>
        <input type="submit" value="QR Oluştur"/>
    }
    <br />
    @if (ViewBag.qrCodeImage != null)
    {
        <img src="@ViewBag.qrCodeImage" alt="" style="width:400px; height:400px;"/>
    }
</div>