MvcOnlineCommercialAutomation/Controllers/ChartController.cs
using MvcOnlineCommercialAutomation.Models.Classes;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MvcOnlineCommercialAutomation.Controllers
{
    public class ChartController : Controller
    {
        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index2()
        {
            var drawchart = new Chart(600, 600);
            drawchart.AddTitle("Kategori - Ürün Stok Sayısı").AddLegend("Stok").AddSeries("Değerler", xValue: new[] { "Mobilya", "Ofis Eşyaları", "Bilgisayar" }, yValues: new[] { 85, 66, 98 }).Write();
            return File(drawchart.ToWebImage().GetBytes(), "image/jpeg");
        }
        Context c = new Context();
        public ActionResult Index3()
        {
            ArrayList xvalue = new ArrayList();
            ArrayList yvalue = new ArrayList();
            var results = c.Products.ToList();
            results.ToList().ForEach(x => xvalue.Add(x.ProductName));
            results.ToList().ForEach(y => yvalue.Add(y.Stock));
            var chart = new Chart(width: 800, height: 800).AddTitle("Stoklar").AddSeries(chartType: "Pie", name: "Stok", xValue: xvalue, yValues: yvalue);
            return File(chart.ToWebImage().GetBytes(), "image/jpeg");
        }
        public ActionResult Index4()
        {
            return View();
        }
        public ActionResult VisualizeProductResult()
        {
            return Json(Productlist(), JsonRequestBehavior.AllowGet);
        }
        public List<chartclass1> Productlist()
        {
            List<chartclass1> cl = new List<chartclass1>();
            cl.Add(new chartclass1()
            {
                productname = "Bilgisayar",
                stock = 120
            });
            cl.Add(new chartclass1()
            {
                productname = "Beyaz Eşya",
                stock = 150
            });
            cl.Add(new chartclass1()
            {
                productname = "Mobilya",
                stock = 70
            });
            cl.Add(new chartclass1()
            {
                productname = "Küçük Ev Aletleri",
                stock = 180
            });
            cl.Add(new chartclass1()
            {
                productname = "Mobil Cihazlar",
                stock = 90
            });
            return cl;
        }
        public ActionResult Index5()
        {
            return View();
        }
        public ActionResult VisualizeProductResult2()
        {
            return Json(Productlist2(), JsonRequestBehavior.AllowGet);
        }
        public List<chartclass2> Productlist2()
        {
            List<chartclass2> cl = new List<chartclass2>();
            using (var c = new Context())
            {
                cl = c.Products.Select(x => new chartclass2
                {
                    prdct = x.ProductName,
                    stck = x.Stock
                }).ToList();
            }
            return cl;
        }
        public ActionResult Index6()
        {
            return View();
        }
        public ActionResult Index7()
        {
            return View();
        }
    }
}

MvcOnlineCommercialAutomation/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>
@{ 
    var chart = new Chart(width: 500, height: 500);
    chart.AddTitle(text: "Kategoriler ve Ürün Sayıları");
    chart.AddLegend(title: "Değerler");
    chart.AddSeries(
        name: "Veriler",
        //chartType: "Bubble",
        //chartType: "Doughnut",
        //chartType: "Pie",
        //chartType: "Area",
        //chartType: "Bar",
        xValue: new[] { "Beyaz Eşya", "Televizyon", "Bilgisayar", "Küçük Ev Aletleri" },
        yValues: new[] { 500, 250, 340, 620 }
        );
    chart.Write();
}

MvcOnlineCommercialAutomation/Views/Chart/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index2</h2>

<div style="width:600px; height:600px">
    <img src="@Url.Action("Index2","Chart")" />
</div>

MvcOnlineCommercialAutomation/Views/Chart/Index3.cshtml
@{
    ViewBag.Title = "Index3";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index3</h2>

<img src="@Url.Action("Index3","Chart")" />

MvcOnlineCommercialAutomation/Views/Chart/Index4.cshtml
@{
    ViewBag.Title = "Index4";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.productname, obj.stock]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };
            //var columnChart = new google.visualization.LineChart(document
            //    .getElementById('linechart_div'));
            //columnChart.draw(data, columnChartOptions);
            var columnChart = new google.visualization.PieChart(document
                .getElementById('piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    @*<div id="linechart_div"></div>*@
    <div id="piechart_div"></div>
</body>
</html>

MvcOnlineCommercialAutomation/Views/Chart/Index5.cshtml
@{
    ViewBag.Title = "Index5";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h2>Ürün - Stok Grafiği Pie</h2>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.prdct, obj.stck]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                //title: "Ürün - Stok Grafiği",
                width: 1200,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            //var columnChart = new google.visualization.LineChart(document
            //    .getElementById('linechart_div'));
            //columnChart.draw(data, columnChartOptions);
            var columnChart = new google.visualization.PieChart(document
                .getElementById('piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    @*<div id="linechart_div"></div>*@
    <div id="piechart_div"></div>
</body>
</html>

MvcOnlineCommercialAutomation/Views/Chart/Index6.cshtml
@{
    ViewBag.Title = "Index6";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h2>Ürün - Stok Grafiği Line</h2>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.prdct, obj.stck]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                //title: "Ürün - Stok Grafiği",
                width: 1200,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('linechart_div'));
            columnChart.draw(data, columnChartOptions);
            //var columnChart = new google.visualization.PieChart(document
            //    .getElementById('piechart_div'));
            //columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="linechart_div"></div>
    @*<div id="piechart_div"></div>*@
</body>
</html>

MvcOnlineCommercialAutomation/Views/Chart/Index7.cshtml
@{
    ViewBag.Title = "Index7";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<br />
<h2>Ürün - Stok Grafiği Column</h2>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.prdct, obj.stck]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                //title: "Ürün - Stok Grafiği",
                width: 1200,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);
            //var columnChart = new google.visualization.PieChart(document
            //    .getElementById('piechart_div'));
            //columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div"></div>
    @*<div id="piechart_div"></div>*@
</body>
</html>